
export const GET_POST_COMMENTS = 'GET_POST_COMMENTS';
export const GET_POST_COMMENTS_SUCCESS = 'GET_POST_COMMENTS_SUCCESS';
export const GET_POST_COMMENTS_LOADING = 'GET_POST_COMMENTS_LOADING';
export const GET_POST_COMMENTS_FAILURE = 'GET_POST_COMMENTS_FAILURE';
