
export const GET_POST_COMMENTS = 'GET_POST_COMMENTS';
export const GET_POST_COMMENTS_SUCCESS = 'GET_POST_COMMENTS_SUCCESS';
export const GET_POST_COMMENTS_LOADING = 'GET_POST_COMMENTS_LOADING';
export const GET_POST_COMMENTS_FAILURE = 'GET_POST_COMMENTS_FAILURE';

export const SAVE_POST_COMMENT = 'SAVE_POST_COMMENT';
export const SAVE_POST_COMMENT_SUCCESS = 'SAVE_POST_COMMENT_SUCCESS';
export const SAVE_POST_COMMENT_LOADING = 'SAVE_POST_COMMENT_LOADING';
export const SAVE_POST_COMMENT_FAILURE = 'SAVE_POST_COMMENT_FAILURE';
