export const SEARCH_POST_TEXT = 'SEARCH_POST_TEXT';
export const CHANGE_POSTS_PAGE = 'CHANGE_POSTS_PAGE';
export const CHANGE_POSTS_SEARCH_TYPE = 'CHANGE_POSTS_SEARCH_TYPE';

export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_LOADING = 'GET_POSTS_LOADING';
export const GET_POSTS_FAILURE = 'GET_POSTS_FAILURE';

export const GET_POST_BY_ID = 'GET_POST_BY_ID';
export const GET_POST_BY_ID_SUCCESS = 'GET_POST_BY_ID_SUCCESS';
export const GET_POST_BY_ID_LOADING = 'GET_POST_BY_ID_LOADING';
export const GET_POST_BY_ID_FAILURE = 'GET_POST_BY_ID_FAILURE';
