export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_LOADING = 'GET_USERS_LOADING';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';
